// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4662.ArmSystem.subsystems;

import org.usfirst.frc4662.ArmSystem.Robot;
import org.usfirst.frc4662.ArmSystem.RobotMap;
import org.usfirst.frc4662.ArmSystem.commands.Arm.*;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class ArmLinearActuator extends Subsystem {

    private final DigitalInput homeLocSw = new DigitalInput(RobotMap.iArmHomeLocSw);
    private final DigitalInput scoopLimSw = new DigitalInput(RobotMap.iArmBotLimSw);
    private final DigitalInput topLimSw = new DigitalInput(RobotMap.iArmTopLimSw);
    
    private final SpeedController armLiftMotor = new Talon(RobotMap.iArmMotor);
    
    private final AnalogPotentiometer armPosPot = new AnalogPotentiometer(RobotMap.iArmPosPot,330,-260);
    
    private final Boolean invMotor = true;
    private final double invSpeed = -1.0;
    
    private double mHomeSetpoint = 0;
    private double mSetpoint = 0; 
    private double mSetpointTbl [] = {10.5, 15.0, 22.0, 27.0};
    private int mSetpIx = 0;
    
    private double mArmPVal = -0.7;
    private double mArmIVal = -0.0;
    private double mArmDVal = -0.5;
    private double mArmTlrnc = 0.80;
    
    public final PIDController armPID = new PIDController(mArmPVal, mArmIVal, mArmDVal, armPosPot, armLiftMotor);
        
    public void ArmSubSys() {
    	armLiftMotor.setInverted(invMotor);
    }
    
    public void initDefaultCommand() {
     	setDefaultCommand(new JoystickArmMove());
    }
    
    public void moveArm(double speed) {
    	
    	if (isTop() == true) {
    		if((invMotor == true & speed < 0) || (invMotor == false & speed > 0)) {
    			speed = 0;
    		}
        } else {
    		if (isBottom() == true) {
        		if((invMotor == true & speed > 0) || (invMotor == false & speed < 0)) {
        			speed = 0;
        		}
    		}
    	}
    	armLiftMotor.set(speed);
    	logArm();
    }
    
    public void moveUp() {
    	double speed = 1 * invSpeed;
      	moveArm(speed);
    }
    
     public void moveDown() {
    	double speed = -1 * invSpeed;
       	moveArm(speed);
    }
    
    public void newHomePID(){
    	this.mHomeSetpoint = this.getArmPID();
    }
    
    public void stopArm() {
       	if (armPID.isEnabled()) {
       		armPID.reset();
       		armPID.disable();
       	}
    	moveArm(0);
    }
    
    public void setArmPID(){
    	armPID.reset();
    	armPosPot.setPIDSourceType(PIDSourceType.kDisplacement);
    	armPID.setInputRange(-2,55);
    	armPID.setOutputRange(-1, 1);
    	armPID.setSetpoint(mSetpoint);
    	armPID.setPID(mArmPVal, mArmIVal, mArmDVal);
    	armPID.setAbsoluteTolerance(mArmTlrnc);
    	armPID.enable();
    }
    
    public void moveHome() {
    	mSetpoint = mHomeSetpoint;
    }
    
     
    public void setARMSetpoint(double setpoint) {
    	mSetpoint = setpoint;
    }
    
    public void setArmSetpointTbl(boolean isUp) {
    	mSetpoint = mSetpointTbl[mSetpIx] + mHomeSetpoint;
    	if (isUp == true) {
    		mSetpIx = (mSetpIx + 1) % mSetpointTbl.length;
    	} else {
    		mSetpIx = mSetpIx - 1;
    		if (mSetpIx < 0) {
    			mSetpIx = mSetpointTbl.length - 1;
    		}
    	}

    }
    
    public boolean isOnTarget(){
    	return armPID.onTarget() || this.isTop() || this.isBottom();
    }
    
    public boolean isTop() {
    	return !topLimSw.get();
    }
    
    public boolean isBottom() {
    	return !scoopLimSw.get();
    }
    
    public boolean isHome() {
    	return !homeLocSw.get();
    }
    
    public double getArmPID(){
    	return armPosPot.pidGet();
    }
    
    public void dashboardDisplay() {
		SmartDashboard.putNumber("Arm P Val", mArmPVal);
		SmartDashboard.putNumber("Arm I Val", mArmIVal);
		SmartDashboard.putNumber("Arm D Val", mArmDVal);
		SmartDashboard.putNumber("Arm Tolerance", mArmTlrnc);
		SmartDashboard.putNumber("Arm Target", mSetpoint);
    }
    
    public void dashboardFetch() {
    	mArmPVal = SmartDashboard.getNumber("Arm P Val", mArmPVal);
		mArmIVal = SmartDashboard.getNumber("Arm I Val", mArmIVal);
		mArmDVal = SmartDashboard.getNumber("Arm D Val", mArmDVal);
		mArmTlrnc = SmartDashboard.getNumber("Arm Tolerance", mArmTlrnc);
		mSetpoint = SmartDashboard.getNumber("Arm Target", mSetpoint);
    }
    
    public void logArm() {
    	SmartDashboard.putNumber("Arm Pot Value", armPosPot.get());
    	SmartDashboard.putNumber("Arm Pot PIDGet", armPosPot.pidGet());
    	SmartDashboard.putNumber("Arm Home Setpoint", mHomeSetpoint);
    	SmartDashboard.putNumber("Arm PID Setpoint", mSetpoint);
       	SmartDashboard.putNumber("Arm Setpt Tbl Ix", mSetpIx);
    	
    	SmartDashboard.putBoolean("Home Switch", isHome());
    	SmartDashboard.putBoolean("Top Lim Switch", isTop());
    	SmartDashboard.putBoolean("Bot Lim Switch", isBottom());
    	
    	if (armPID.isEnabled()) {
           	SmartDashboard.putNumber("Arm PID Loop Value", armPID.get());
          	SmartDashboard.putBoolean("Arm PID On Target", armPID.onTarget());
    	}
    	
     }
 }

